---
name: test

on:
  pull_request: {}
  push:
    branches:
      - main

permissions: {}

jobs:
  test:
    runs-on: ubuntu-24.04
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: aquaproj/aqua-installer@e2d0136abcf70b7a2f6f505720640750557c4b33 # v3.1.1
        with:
          aqua_version: v2.45.0
          aqua_opts: ""
      - run: go version
      - run: command -v go
      - run: aqua which go
      - run: mage -version
      - run: command -v mage
      - run: aqua which mage
      - run: mage -l
      - run: mage hello
